#!/bin/sh
URLS="http://mail.python.org/pipermail/python-dev/2012-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2012-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2012-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2012-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2011-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2010-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2009-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2008-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2007-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2006-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2005-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2004-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2003-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2002-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2001-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-March.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-February.txt.gz \
	http://mail.python.org/pipermail/python-dev/2000-January.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-December.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-November.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-October.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-September.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-August.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-July.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-June.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-May.txt.gz \
	http://mail.python.org/pipermail/python-dev/1999-April.txt.gz \
	http://mail.python.org/pipermail/python-dev/1995-March.txt.gz"

mkdir -p emails
cd emails
for url in $URLS;
do
	wget -nc $url
done
